---
- name: install on server linux
  hosts: web
  become: true
  tasks:
    - name: install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: execute Apache
      service:
        name: apache2
        state: started
        enabled: yes
