---
- name: نصب Apache روی سرور
  hosts: web
  become: true
  tasks:
    - name: نصب Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: فعال و اجرا کردن Apache
      service:
        name: apache2
        state: started
        enabled: yes
